Componente LinkedIn
tech-pro-bem/institutional-tech-pro-bem pull request #30
Opened 2023-12-05 20:16 UTC by bruna40

2023-12-06 11:09 UTC, ronansalvador commented on app/components/SessionLinkedin/style.module.css
> +        justify-content: center;
eu trocaria o `justify-content: center;` por `justify-content: space-evenly;`
Removeria o transform,  e aumentaria o max-widht para 70.875rem, acredito que ficaria com o layout mais fluido

2023-12-06 11:09 UTC, ronansalvador commented on app/components/SessionLinkedin/style.module.css
> +
adiconar:

`.section__container_text {
    min-width: 20rem;
    max-width: 24rem;
    padding-inline: 0;
  }`
  
  trabalhar com um tamanho maximo e minimo para mater o layout de tablet

2023-12-06 11:09 UTC, ronansalvador commented on app/components/SessionLinkedin/style.module.css
> +        gap: 7.5rem;
por utilizar o `justify-content: space-evenly;` na media de 48em, podemos remover o gap.

2023-12-14 21:37 UTC, marcelluscaio requested changes

2023-12-14 21:37 UTC, marcelluscaio commented on app/components/SessionLinkedin/style.module.css
> +
1.635rem eh um valor quebrado. Sera que a gente queria 1.625 (26px)?

2023-12-14 21:37 UTC, marcelluscaio commented on app/components/SessionLinkedin/style.module.css
> +    padding-right: 0.2rem;
Em vez de padding right aqui devemos usar gap no link (gap de .375rem para atingir 6px)

2023-12-14 21:37 UTC, marcelluscaio commented on app/components/SessionLinkedin/style.module.css
> +    align-items: center;
Qual o papel do align items aqui?

2023-12-14 21:37 UTC, marcelluscaio commented on app/components/SessionLinkedin/style.module.css
> +        max-width: 70.875rem;
Esse valor nao esta batendo com o valor da largura no figma

2023-12-14 21:37 UTC, marcelluscaio commented on app/components/SessionLinkedin/style.module.css
> +        gap: 7.5rem;
Concordo, mas acho que a melhor forma de fazermos isso tendo mais controle seria nao usar space-evenly aqui (fica muito dificil calcular qual eh o espacamento aplicado exatamente). O que acham de aplicar justify content center com um gap de 6.25vw (esse valor da 120px nas telas de 1920px)

2023-12-14 21:37 UTC, marcelluscaio commented on app/components/SessionLinkedin/style.module.css
> +        max-width: 24.1875rem;
Tem um espaco em branco na caixa de texto do figma. Sugiro aplicarmos max-width de 22.5rem (360px)

2023-12-14 21:37 UTC, marcelluscaio commented on app/components/SessionLinkedin/style.module.css
> +
o <p> filho do section__container_text esta com a aparencia diferente do Figma. Sugiro usarmos text-wrap: initial nele

2023-12-15 17:15 UTC, bruna40 commented on app/components/SessionLinkedin/style.module.css
> +    align-items: center;
Vi agora, não tem papel nenhum na classe e já retirei

2023-12-15 17:31 UTC, bruna40 commented on app/components/SessionLinkedin/style.module.css
> +        max-width: 70.875rem;
eu acho que coloquei pq estava olhando para a sessão 'nossos valores' e achei esquisito a diferença de tamanho quando colocou um embaixo do outro

2023-12-15 20:17 UTC, closed without merging